# Generated by Django 4.2.13 on 2024-05-14 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmpimage',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bmpimage',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
