# Generated by Django 4.2.13 on 2024-05-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmp', '0002_bmpimage_text_bmpimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmpimage',
            name='res_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
