# Generated by Django 4.2.13 on 2024-05-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmp', '0003_bmpimage_res_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmpimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bmpimage',
            name='res_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
